@echo off
echo [1/5] Initializing Git...
git init
echo [2/5] Adding files...
git add .
echo [3/5] Committing changes...
git commit -m "PIC32CM Dual-UART Bridge Finalized"
echo [4/5] Setting up remote...
git remote add origin https://github.com/PriyaSelvakumar123/MICROCHIP-PROJECT.git
git remote set-url origin https://github.com/PriyaSelvakumar123/MICROCHIP-PROJECT.git
echo [5/5] Pushing to GitHub...
git branch -M main
git push -u origin main
echo Done!
pause
