#include "definitions.h"
#include <stdint.h>
#include <string.h>

// Baud: 115200 @ 48MHz
#define UART_BAUD_115200 63019

/* --- DUAL UART INITIALIZATION (SERCOM2 on PA08/PA09, SERCOM5 on PB02/PB03) --- */
void Standalone_Init(void) {
    // Enable MCLK for SERCOM2, SERCOM3, and SERCOM5
    MCLK_REGS->MCLK_APBCMASK |= MCLK_APBCMASK_SERCOM2_Msk |
                                 MCLK_APBCMASK_SERCOM3_Msk |
                                 MCLK_APBCMASK_SERCOM5_Msk;

    // Enable GCLK for SERCOM2 (ch19), SERCOM3 (ch20), SERCOM5 (ch22)
    GCLK_REGS->GCLK_PCHCTRL[19] = GCLK_PCHCTRL_GEN(0x0) | GCLK_PCHCTRL_CHEN_Msk;
    GCLK_REGS->GCLK_PCHCTRL[20] = GCLK_PCHCTRL_GEN(0x0) | GCLK_PCHCTRL_CHEN_Msk;
    GCLK_REGS->GCLK_PCHCTRL[22] = GCLK_PCHCTRL_GEN(0x0) | GCLK_PCHCTRL_CHEN_Msk;
    while (!(GCLK_REGS->GCLK_PCHCTRL[19] & GCLK_PCHCTRL_CHEN_Msk));
    while (!(GCLK_REGS->GCLK_PCHCTRL[20] & GCLK_PCHCTRL_CHEN_Msk));
    while (!(GCLK_REGS->GCLK_PCHCTRL[22] & GCLK_PCHCTRL_CHEN_Msk));

    // SERCOM2 (PA08/PA09) and SERCOM3 (PB08/PB09) are already physically configured 
    // in PORT_Initialize() using `PORT_SEC_REGS`. 
    // For SERCOM5 (PB02/PB03), we must also configure pins using secure registers:
    
    // SERCOM5: PB02=PAD0(TX), PB03=PAD1(RX) -- MUX D (0x3)
    PORT_SEC_REGS->GROUP[1].PORT_PMUX[1] = 0x33U; // MUX D for PB02 and PB03
    PORT_SEC_REGS->GROUP[1].PORT_PINCFG[2] |= PORT_PINCFG_PMUXEN_Msk; // Enable Peripheral Muxing
    PORT_SEC_REGS->GROUP[1].PORT_PINCFG[3] |= PORT_PINCFG_PMUXEN_Msk;

    // Init SERCOM2 (ESP-01S on PA08/PA09)
    SERCOM2_REGS->USART_INT.SERCOM_CTRLA = SERCOM_USART_INT_CTRLA_SWRST_Msk;
    while (SERCOM2_REGS->USART_INT.SERCOM_SYNCBUSY & SERCOM_USART_INT_SYNCBUSY_SWRST_Msk);
    SERCOM2_REGS->USART_INT.SERCOM_CTRLA = SERCOM_USART_INT_CTRLA_MODE(0x1) | SERCOM_USART_INT_CTRLA_TXPO(0x0) | SERCOM_USART_INT_CTRLA_RXPO(0x1) | SERCOM_USART_INT_CTRLA_DORD_Msk;
    SERCOM2_REGS->USART_INT.SERCOM_CTRLB = SERCOM_USART_INT_CTRLB_CHSIZE(0x0) | SERCOM_USART_INT_CTRLB_TXEN_Msk | SERCOM_USART_INT_CTRLB_RXEN_Msk;
    while (SERCOM2_REGS->USART_INT.SERCOM_SYNCBUSY & SERCOM_USART_INT_SYNCBUSY_CTRLB_Msk);
    SERCOM2_REGS->USART_INT.SERCOM_BAUD = (uint16_t)UART_BAUD_115200;
    SERCOM2_REGS->USART_INT.SERCOM_CTRLA |= SERCOM_USART_INT_CTRLA_ENABLE_Msk;
    while (SERCOM2_REGS->USART_INT.SERCOM_SYNCBUSY & SERCOM_USART_INT_SYNCBUSY_ENABLE_Msk);

    // Init SERCOM3 (PC/PuTTY on PA22/PA23)
    SERCOM3_REGS->USART_INT.SERCOM_CTRLA = SERCOM_USART_INT_CTRLA_SWRST_Msk;
    while (SERCOM3_REGS->USART_INT.SERCOM_SYNCBUSY & SERCOM_USART_INT_SYNCBUSY_SWRST_Msk);
    SERCOM3_REGS->USART_INT.SERCOM_CTRLA = SERCOM_USART_INT_CTRLA_MODE(0x1) | SERCOM_USART_INT_CTRLA_TXPO(0x0) | SERCOM_USART_INT_CTRLA_RXPO(0x1) | SERCOM_USART_INT_CTRLA_DORD_Msk;
    SERCOM3_REGS->USART_INT.SERCOM_CTRLB = SERCOM_USART_INT_CTRLB_CHSIZE(0x0) | SERCOM_USART_INT_CTRLB_TXEN_Msk | SERCOM_USART_INT_CTRLB_RXEN_Msk;
    while (SERCOM3_REGS->USART_INT.SERCOM_SYNCBUSY & SERCOM_USART_INT_SYNCBUSY_CTRLB_Msk);
    SERCOM3_REGS->USART_INT.SERCOM_BAUD = (uint16_t)UART_BAUD_115200;
    SERCOM3_REGS->USART_INT.SERCOM_CTRLA |= SERCOM_USART_INT_CTRLA_ENABLE_Msk;
    while (SERCOM3_REGS->USART_INT.SERCOM_SYNCBUSY & SERCOM_USART_INT_SYNCBUSY_ENABLE_Msk);

    // Init SERCOM5 (second device on PB02/PB03)
    SERCOM5_REGS->USART_INT.SERCOM_CTRLA = SERCOM_USART_INT_CTRLA_SWRST_Msk;
    while (SERCOM5_REGS->USART_INT.SERCOM_SYNCBUSY & SERCOM_USART_INT_SYNCBUSY_SWRST_Msk);
    SERCOM5_REGS->USART_INT.SERCOM_CTRLA = SERCOM_USART_INT_CTRLA_MODE(0x1) | SERCOM_USART_INT_CTRLA_TXPO(0x0) | SERCOM_USART_INT_CTRLA_RXPO(0x1) | SERCOM_USART_INT_CTRLA_DORD_Msk;
    SERCOM5_REGS->USART_INT.SERCOM_CTRLB = SERCOM_USART_INT_CTRLB_CHSIZE(0x0) | SERCOM_USART_INT_CTRLB_TXEN_Msk | SERCOM_USART_INT_CTRLB_RXEN_Msk;
    while (SERCOM5_REGS->USART_INT.SERCOM_SYNCBUSY & SERCOM_USART_INT_SYNCBUSY_CTRLB_Msk);
    SERCOM5_REGS->USART_INT.SERCOM_BAUD = (uint16_t)UART_BAUD_115200;
    SERCOM5_REGS->USART_INT.SERCOM_CTRLA |= SERCOM_USART_INT_CTRLA_ENABLE_Msk;
    while (SERCOM5_REGS->USART_INT.SERCOM_SYNCBUSY & SERCOM_USART_INT_SYNCBUSY_ENABLE_Msk);
}

void PC_Print(const char *str) {
    while (*str) {
        while (!(SERCOM3_REGS->USART_INT.SERCOM_INTFLAG & SERCOM_USART_INT_INTFLAG_DRE_Msk));
        SERCOM3_REGS->USART_INT.SERCOM_DATA = (uint16_t)*str++;
    }
}

int main(void) {
    SYS_Initialize(NULL);
    Standalone_Init();

    PC_Print("\r\n--- UART TRANSPARENT BRIDGE ---\r\n");
    PC_Print("SERCOM2 (PA08/PA09) <-> PuTTY (SERCOM3 PA22/PA23)\r\n");
    PC_Print("SERCOM5 (PB02/PB03) <-> PuTTY (SERCOM3 PA22/PA23)\r\n");
    PC_Print("Type your commands now...\r\n\r\n");

    while (1) {
        /* --- Bridge 1: PuTTY (SERCOM3) <-> ESP (SERCOM2 on PA08/PA09) --- */

        // 1a. Read from PuTTY, Send to SERCOM2 (ESP)
        if (SERCOM3_REGS->USART_INT.SERCOM_INTFLAG & SERCOM_USART_INT_INTFLAG_RXC_Msk) {
            uint8_t data = (uint8_t)SERCOM3_REGS->USART_INT.SERCOM_DATA;

            // Send to SERCOM2 (ESP)
            while (!(SERCOM2_REGS->USART_INT.SERCOM_INTFLAG & SERCOM_USART_INT_INTFLAG_DRE_Msk));
            SERCOM2_REGS->USART_INT.SERCOM_DATA = (uint16_t)data;

            // Also send to SERCOM5 (second device on PB02/PB03)
            while (!(SERCOM5_REGS->USART_INT.SERCOM_INTFLAG & SERCOM_USART_INT_INTFLAG_DRE_Msk));
            SERCOM5_REGS->USART_INT.SERCOM_DATA = (uint16_t)data;

            // If Enter (\r), send \n to both devices and echo to PuTTY
            if (data == '\r') {
                while (!(SERCOM2_REGS->USART_INT.SERCOM_INTFLAG & SERCOM_USART_INT_INTFLAG_DRE_Msk));
                SERCOM2_REGS->USART_INT.SERCOM_DATA = (uint16_t)'\n';

                while (!(SERCOM5_REGS->USART_INT.SERCOM_INTFLAG & SERCOM_USART_INT_INTFLAG_DRE_Msk));
                SERCOM5_REGS->USART_INT.SERCOM_DATA = (uint16_t)'\n';

                while (!(SERCOM3_REGS->USART_INT.SERCOM_INTFLAG & SERCOM_USART_INT_INTFLAG_DRE_Msk));
                SERCOM3_REGS->USART_INT.SERCOM_DATA = (uint16_t)'\n';
            }
        }

        // 1b. Read from SERCOM2 (ESP), Send to PuTTY
        if (SERCOM2_REGS->USART_INT.SERCOM_INTFLAG & SERCOM_USART_INT_INTFLAG_RXC_Msk) {
            uint8_t data = (uint8_t)SERCOM2_REGS->USART_INT.SERCOM_DATA;
            while (!(SERCOM3_REGS->USART_INT.SERCOM_INTFLAG & SERCOM_USART_INT_INTFLAG_DRE_Msk));
            SERCOM3_REGS->USART_INT.SERCOM_DATA = (uint16_t)data;
        }

        /* --- Bridge 2: SERCOM5 (PB02/PB03) -> PuTTY (SERCOM3) --- */

        // 2. Read from SERCOM5 (PB02/PB03), Send to PuTTY
        if (SERCOM5_REGS->USART_INT.SERCOM_INTFLAG & SERCOM_USART_INT_INTFLAG_RXC_Msk) {
            uint8_t data = (uint8_t)SERCOM5_REGS->USART_INT.SERCOM_DATA;
            while (!(SERCOM3_REGS->USART_INT.SERCOM_INTFLAG & SERCOM_USART_INT_INTFLAG_DRE_Msk));
            SERCOM3_REGS->USART_INT.SERCOM_DATA = (uint16_t)data;
        }
    }
    return 0;
}